// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-subscriptions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_subscriptions_default = defineTool({
  name: "list_subscriptions",
  title: "List subscriptions",
  description: "List all subscriptions for the signed-in user, including name, cost, billing cycle, category and next renewal date.",
  inputSchema: {
    category: z.string().optional().describe("Optional category filter (e.g. Entertainment, Software).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("subscriptions").select("id, name, cost, billing_cycle, category, next_renewal_date, alerts_enabled").eq("user_id", ctx.getUserId()).order("next_renewal_date", { ascending: true });
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { subscriptions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-subscription.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_subscription_default = defineTool2({
  name: "create_subscription",
  title: "Create subscription",
  description: "Create a new subscription for the signed-in user. Cost is in the user's currency; billing_cycle is 'monthly' or 'yearly'.",
  inputSchema: {
    name: z2.string().trim().min(1).describe("Service name, e.g. Netflix."),
    cost: z2.number().positive().describe("Recurring cost per billing cycle."),
    billing_cycle: z2.enum(["monthly", "yearly"]).describe("How often the subscription renews."),
    category: z2.string().trim().min(1).describe("Category, e.g. Entertainment."),
    next_renewal_date: z2.string().describe("Next renewal date in YYYY-MM-DD format."),
    alerts_enabled: z2.boolean().optional().describe("Whether renewal alerts are on.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("subscriptions").insert({
      user_id: ctx.getUserId(),
      name: input.name,
      cost: input.cost,
      billing_cycle: input.billing_cycle,
      category: input.category,
      next_renewal_date: input.next_renewal_date,
      alerts_enabled: input.alerts_enabled ?? true
    }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Created subscription ${data.name} (${data.id}).` }],
      structuredContent: { subscription: data }
    };
  }
});

// src/lib/mcp/tools/delete-subscription.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var delete_subscription_default = defineTool3({
  name: "delete_subscription",
  title: "Delete subscription",
  description: "Permanently delete one of the signed-in user's subscriptions by id.",
  inputSchema: {
    id: z3.string().uuid().describe("Subscription id to delete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { error } = await supabaseForUser3(ctx).from("subscriptions").delete().eq("id", id).eq("user_id", ctx.getUserId());
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return { content: [{ type: "text", text: `Deleted subscription ${id}.` }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yyxdjgximzellsdnjhbl";
var mcp_default = defineMcp({
  name: "subsentry-mcp",
  title: "SubSentry MCP",
  version: "0.1.0",
  instructions: "Tools for SubSentry, a subscription tracker. Use list_subscriptions to read the signed-in user's subscriptions, create_subscription to add one, and delete_subscription to remove one.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_subscriptions_default, create_subscription_default, delete_subscription_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
